[package]
name = "blackjack-tui"
authors = ["Adam Hill"]
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8" }
ratatui = { version = "0.29", features = ["unstable-widget-ref"] }